### ISSUE TITLE
Not registering devices to the cloud after a while

### ISSUE THREAD

**Issue by jcorde** [CESARBR/knot-fog-connector#8]
**Occurred once**

New devices are registered to the fog and appear on the gateway control screen (knot.local). But are not being registered to the cloud after some time running.

I suspect that adding multiple devices to the gateway may help at reproducing it.

**Comment by netoax** [comment]
@ramonhpr can you give us details about the scenario this issue occurred?

**Comment by netoax** [comment]
This bug was fixed on [knot-gateway-buildroot](https://github.com/CESARBR/knot-gateway-buildroot/pull/17).
